# Vanilla Minecraft server
version: '3.7'
services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
      - "25575:25575"
    environment:
      ALLOW_NETHER: "TRUE"
      ENABLE_RCON: "TRUE"
      EULA: "TRUE"
      MEMORY: "3G"
      RCON_PASSWORD: "minecraft" # Set your own password
    deploy:
      resources:
        limits:
          memory: "4G"
          cpus: "1"
    volumes:
      - "minecraft:/data"
volumes:
  minecraft:
    driver: "azure_file"
    driver_opts:
      share_name: "mc-vanilla"
      storage_account_name: "minecraftstorage" # Set your own Storage Account name
