name: Test and Deploy PowerShell Azure Function App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "."

jobs:
  test:
    name: PSScriptAnalyzer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@2044ae068e37d0161fa2127de04c19633882f061
        with:
          path: .\
          recurse: true
          settings: .PSScriptAnalyzerSettings.psd1
          output: results.sarif

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Zip app code
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          Compress-Archive -Path . -DestinationPath './release.zip'
          popd
      - name: Azure Functions Action
        id: fa
        uses: Azure/functions-action@v1.4.4
        with:
          app-name: ${{ Secrets.AZURE_FUNCTION_APP_NAME }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/release.zip"
          publish-profile: ${{ Secrets.AZURE_FUNCTION_APP_PUBLISH_PROFILE }}
          respect-funcignore: true
